### ISSUE TITLE
Camera gets stuck in "Connecting" 

### ISSUE THREAD

**Issue by dksdarkness** [ThibaudM/timelapse-sony#1]
The camera doesn't get connected to the android app. The message is "Connecting".

My firmware versions are:
* NEX-6: v. 1.02
* Mobile: Samsung Galaxy S2 (GT-i9100)
* Android: 4.1.2
* Smart remote Controller (NEX-6 app): 2.10

If I use "Smart remote Controller" app the camera connects.

In your app, I chose "NEX-6" camera option

Do you need more information to help you?

Thanks

**Comment by retracked** [comment]
Let's mark this issue as closed to clean up a bit.
