### ISSUE TITLE
QX1 Support

### ISSUE THREAD

**Issue by MrPrimate** [ThibaudM/timelapse-sony#10]
Any chance of adding QX1 Support?

**Comment by retracked** [comment]
Have you tried using the app by choosing "QX-10 / QX-100" in the drop down menu? Odds are good QX-1 uses the same settings.

**Comment by MrPrimate** [comment]
Yep, does work, it just seems that either my phone of the camera body it self can occasionally have a real hard time connecting. It seems to be worse when your not using Sony's official app.

**Comment by davidbuzz** [comment]
my QX1 seems to need me to select "QX-30" from the menu, but then works fine.    If I select "QX-10 / QX-100" then I get "Connection to WebService failed. Check your device model."
