### ISSUE TITLE
Sony A77 ii

### ISSUE THREAD

**Issue by legi1** [ThibaudM/timelapse-sony#11]
Please add the Sony A77 ii to your App

Thank you 
Peter

**Comment by retracked** [comment]
Have you tried choosing one of the other cameras via the dropdown menu? Only if we know which setting works we can add the A77m2.

**Comment by legi1** [comment]
I tried all other cameras in the menu none worked.

**Comment by retracked** [comment]
Did you try it the same way as with the orginal app by Sony? I don't 
know were to get the correct setting from if really none of the current 
ones are working. Maybe Thibaud knows how.

Am 12.04.2015 um 16:33 schrieb legi1:

**Comment by Fotolisk** [comment]
It would be great for me too if the A77m2 could connect to your App, thanks!

**Comment by Fotolisk** [comment]
Is there no update for the sony a77ii?

**Comment by ThibaudM** [comment]
Is Sony Play Memories App working with a77ii ?

**Comment by retracked** [comment]
Apparently the A77II has a "Crtl w/ Smartphone" option in the menu that enables use with the Playmemories app (source: https://www.youtube.com/watch?v=5ScKoqbnvPI).

I don't know how to get the needed IP. Do we need to watch the behaviour of Sony's original app for each camera that isn't supported in their official API? For the supported cameras we simply could ask the API for the IP and then even no model selection would be needed.

**Comment by ThibaudM** [comment]
Can you try to follow these steps: https://github.com/ThibaudM/timelapse-sony#adding-a-new-camera-device
