### ISSUE TITLE
Keep screen active, update camera list

### ISSUE THREAD

**Issue by erniberni** [ThibaudM/timelapse-sony#14]
Hi,
I am not sure if you included that the program should work even when the Android is going to sleep (ie screen off).
When my Android (Nexus 7) goes to sleep with screen off, the application pauses work and no more photos are taken.
I use an additional app to control sleep mode, but it would be perfect to do this in the timelapse app, means operate even with display shut off.

Regards
Reinhard

**Comment by retracked** [comment]
Hi Reinhard,

i'll take the freedom to answer. I implemented a few new features some time ago, one of which was the exact same thing you suggest. In principle the code is ready, except for some bugs that should be fixed for release. But in the meantime development has slowed down a bit. Maybe we should finally take the step and finish this work for the next version.

**Comment by erniberni** [comment]
Hi,
sounds good. I'm looking forward for the first tests.
One remark for your information: I'm using a Sony DSC-HX90 with the DSC-HX400V selected in the app. It seems to be compatible.

**Comment by retracked** [comment]
I'll let Thibaud decide if he wants to add your camera to the list. There are a lot of other new cameras that should be compatible to the app. Maybe we could group some cameras into a single list item (e.g. all the NEX cameras).

**Comment by erniberni** [comment]
imho it is not imperative that the screen stays always on. Maybe it will be even better for long-lasting timelapse to switch off the screen to save battery but keep the app running.

**Comment by retracked** [comment]
If i remember correctly, the implemented behaviour was the following: The app stays active while doing timelapse shots (in contrast to the current behaviour) and there is a switch that keeps the display on as well - if desired.

**Comment by ThibaudM** [comment]
I planned to enhance this by adding a thread only for this purpose and put information in notification bar
