### ISSUE TITLE
Can't connect my NEX-6

### ISSUE THREAD

**Issue by pr498te** [ThibaudM/timelapse-sony#17]
Hello, trying to connect my NEX-6, but it's not possible. It shows always the comment "prove your camera model" or "Connection to WebService failed. ...". I tried several different models in your app, but nothing works. I also installed your app "Retrieve Sony Camera IP" without any result.
By the way, connection works with Sonys PlayMemomiers. Any ideas?
Thanks for your support!

**Comment by retracked** [comment]
What's the version of "Smart Remot Control" on your camera? Is it the most recent one? I'm using the app for my NEX-6 frequently without problems.

**Comment by pr498te** [comment]
Hi, it's version 4.10. I thing the latest one, not shure the most recent one.

**Comment by pr498te** [comment]
Ok, that's it! Now I understand! It only works with the app "Smart Remot Control" ? Building the connection via "Smart Remot Control" timelaps works as well!
