### ISSUE TITLE
[Resolved] Doesn't work with NEX-6

### ISSUE THREAD

**Issue by elclaudio** [ThibaudM/timelapse-sony#2]
Hi,

Got nex-6 and firmware v1.03, and the app says that connection to webservice has failed. I don't know if it worked with previous firmwares, never tried.

If you can do something, it would be appreciated

**Comment by mykola-rykov** [comment]
Hi,

Oh my :) Finally it works for me! And it works great, thank you for your
awesome work!
I'm sorry, I was so stupid when I firstly tried to make it work - I haven't
Smart Remote App installed on my camera :D, I didn't get that it is
required.

2014-12-19 19:09 GMT+02:00 elclaudio <notifications@github.com>:

> @mykola-rykov <https://github.com/mykola-rykov>
>
> yes, it was my fault, it works. You should go in Menu / Application /
> Smart Remote control and click on it. Wait a few seconds and then it show a
> message with SSID, password, device name and a little wifi logo on top
> right. Then you should launch Timelapse on your smartphone or tablett and
> search for devices. Thats all.
>
> Greetings from France
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ThibaudM/timelapse-sony/issues/2#issuecomment-67666382>
> .
>



-- 
Regards,
Mykola Rykov

**Comment by mykola-rykov** [comment]
So, if you see "Connection to WebService failed. Check your device model" on your NEX-6, check if free Sony app "Smart Remote Control" is installed on your camera: https://www.playmemoriescameraapps.com/portal/usbdetail.php?eid=IS9104-NPIA09014_00-F00002

**Comment by retracked** [comment]
Maybe a more prominent message would be needed to make clear the "Smart Remote?" app on the camera is needed.

**Comment by ThibaudM** [comment]
I changed the description of application on Play Store (soon published).
