### ISSUE TITLE
HX60v, stops after about an hour, 

### ISSUE THREAD

**Issue by Gorlist** [ThibaudM/timelapse-sony#20]
Just installed and downloaded the app onto my Umi Zero running rom v3.10, Android 4.4.2.

 Works perfect however I'm finding that after about an hour when I come back to the phone I find it sitting on the first screen, **Connection is OK**, but the camera is no longer taking pictures.

I can start another time lapse fine.

Any suggestions. Thanks

**Comment by Gorlist** [comment]
Okay tried another phone and it seem fine! so please ignore.

**Comment by ThibaudM** [comment]
Ok, it's a good news. 
In fact I think you had a quick (>10sec) disconnection from wifi that's why the app came back to the first screen and you was stuck.
