### ISSUE TITLE
Sony Alpha 7: Cannot connect to WebService

### ISSUE THREAD

**Issue by lukasstevens** [ThibaudM/timelapse-sony#25]
Hello,
I tried to use the app with a Sony Alpha 7. Unfortunately I get the error: `cannot connect to WebService`. Is the camera still supported?

If I can help by providing additional information I would gladly do so.

Thank you for your time.

**Comment by retracked** [comment]
It still works fine for my A7II.

Do you use the newest "Smart Remote Control" app on your camera?

**Comment by lukasstevens** [comment]
Thank you for your answer. I managed to connect it.
