### ISSUE TITLE
A6500 reports 'not implemented' 

### ISSUE THREAD

**Issue by Deph0** [ThibaudM/timelapse-sony#27]
Hi, i have had my hands on the A6500 for some time, I went ahead and tested the RetrieveSonyCameraIP app and it resolved to  `http://192.168.122.1:8080/sony/camera`

Unfortunately, it seems that this url is not functional with the 'Sony Smart Remote Control' app as the url resolved to `{"error":[501,"Not Implemented"]}` on my phone browser.

Ideas?

**Comment by ThibaudM** [comment]
Hi,
Is PlayMemories app working?
If it's the case, there should be a solution.
If it's not http://192.168.122.1:8080/sony/camera, it could be:
- http://10.0.0.1:10000/camera
- http://10.0.0.1:10000/sony/camera

**Comment by Deph0** [comment]
Neither seems to yield a response.

**Comment by ThibaudM** [comment]
Is PlayMemories app working?

**Comment by Deph0** [comment]
Yes, PlayMemories works, is there a way i can see what ip it is talking to the camera with?

**Comment by ThibaudM** [comment]
Yes, using an app like wireshark for Android but it's fastidious.
You should try the app at step 2 (https://github.com/ThibaudM/timelapse-sony#adding-a-new-camera-device), maybe you will see the right IP.

**Comment by obs1dium** [comment]
Instead of hardcoding the URIs, why don't you retrieve them using SSDP?

**Comment by Deph0** [comment]
@obs1dium Hi :)

From #22 where i asked the same question;
> The sony dev camera api doesn't support the only camera I have: RX100 mk2. And I think this is the case for some others, you can compare the list of supported devices with this one. This is mostly due to the SSDP response which answers a bad address. See this topic for more information.
I am also aware that it is painful to choose the device when a service can do it.

**Comment by obs1dium** [comment]
Fair enough.
