### ISSUE TITLE
Multiple cameras control?

### ISSUE THREAD

**Issue by hb0** [ThibaudM/timelapse-sony#28]
Hi there,

I have a general question (there is not much information on the Sony SDK out there): Is it possible to control multiple camera at the same time, e.g. to trigger single pictures with 1Hz frequency automatically on e.g. two cameras until there is a stop command?

Many thanks in advance for any replies.

**Comment by ThibaudM** [comment]
Hi,

In fact, the camera creates a wifi access point then your smartphone establish a connection. Theoretically, you can:
- Connect to camera 1
- Send action "Take Picture"
- Connect to camera 2
- Send action "Take Picture"
- Connect to camera 1
- Send action "Take Picture"
...

But, as you smartphone need few seconds to be connected to a WiFi access point, this can not be managed at 1Hz. So, to conclude: It could be possible if you want a frequency at 1/10Hz or less.

**Comment by hb0** [comment]
Thanks for the reply. Unfortunately, we need to start all cameras within a few milliseconds and than automatically collect pictures with 1Hz. I guess we need to find another camera then. Thanks.

**Comment by retracked** [comment]
Obviously not an issue...
