### ISSUE TITLE
Stops shooting photos when screen off.

### ISSUE THREAD

**Issue by grafgraffy** [ThibaudM/timelapse-sony#3]
On a Galaxy S5 when the screen turns automatically off the app stops shooting photos (RX100MK2). After turning on the screen it starts shooting from the last point without trouble. Tried to disable all Wifi Energy Saving Components STAMINA Mode and so on but not resolution yet. Do you have an idea hot to solve this or can you program a wakelock option in your app?

Thanks for the goodwork so far, nice app.

**Comment by retracked** [comment]
Resolved with upcoming update.
