### ISSUE TITLE
License: GPLv2 only or GPLv2+?

### ISSUE THREAD

**Issue by relan** [ThibaudM/timelapse-sony#44]
Could you please specify whether app code is under _GPLv2 only_ or _GPLv2 or later_? We need this question to be cleared for F-Droid.

The problem here is that GPLv2 is incompatible with Apache 2.0 (the license of Android Support Library): https://www.apache.org/licenses/GPL-compatibility.html.

I assume that you mean GPLv2+ (i.e. GPLv3 can be applied to resolve the Apache 2.0 compatibility problem), but would like to get an explicit confirmation.

**Comment by ThibaudM** [comment]
It is ok now, I explicitly changed the license to GPLv3 89083b4da3bc31dcd4cc44abacf4c347d476d7dd

**Comment by relan** [comment]
So, is it _GPLv3 only_ or _GPLv3+_ now?

**Comment by ThibaudM** [comment]
Is GPLv3 _only_ compatible enough with F-Droid?

Sorry for my misunderstanding but I read:
> GPLv3 can be applied to resolve the Apache 2.0 compatibility problem.

**Comment by relan** [comment]
> Is GPLv3 only compatible enough with F-Droid?

Any of _GPLv2+_, _GPLv3 only_ or _GPLv3+_ is fine. We just need to specify which of them should be applied.

The difference between _X only_ and _X or later_ is that the latter allows users to apply later versions of the same license once they appear. You should decide whether you want to give this opportunity.

**Comment by ThibaudM** [comment]
Ok, so consider this license _GPLV3 only_

**Comment by relan** [comment]
Thanks! I'll push an update to 3.0.5 tonight.
