### ISSUE TITLE
RX10 Raw

### ISSUE THREAD

**Issue by fjp** [ThibaudM/timelapse-sony#6]
I want to shoot in Raw and set the camera accordimgly. App switches camera quality setting to Raw+Jpep. This "automatic" switch dies not happen when shooting with jpeg quality.

**Comment by retracked** [comment]
This most definitely only depends on your cameras software, not this app. Have you tried to update the App on your RX10 (if this is possible)?

I think the camera needs to make a jpg to have a image preview for the client/smartphone.

**Comment by fjp** [comment]
The camera runs the latest firmware version 2.0. 
I am not sure but I don't think I can update the module/app that connects the camera to the phone specifically.
Though jpeg quality is also fine...

**Comment by retracked** [comment]
Raw+jpg should give you both a RAW and a JPG file, so you just need to delete the JPG files afterwards if you don't need them. As this also may require to redesign the app i'll close the issue for now since this is not planned.
But nevertheless thanks for your feedback!
